import {
  DashboardOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  AppleOutlined,
  CreditCardOutlined,
  TrophyOutlined,
  BellOutlined,
  CustomerServiceOutlined,
  FileTextOutlined,
  QuestionCircleOutlined,
  TranslationOutlined,
  BarChartOutlined,
  RobotOutlined,
  AuditOutlined,
  SettingOutlined,
} from "@ant-design/icons";

// Central navigation source of truth for the admin sidebar.
// `section` groups items under Menu.ItemGroup labels.
// `path` drives routing; `enabled: false` marks screens not yet built —
// the route/menu item exists so the architecture is ready to extend,
// but no page UI has been created for it in this phase.
export const navigationItems = [
  {
    key: "dashboard",
    label: "Dashboard",
    icon: DashboardOutlined,
    path: "/admin",
    section: "MAIN",
    enabled: true,
  },
  {
    key: "users",
    label: "Users",
    icon: TeamOutlined,
    path: "/admin/users",
    section: "MANAGEMENT",
    enabled: false,
  },
  {
    key: "workouts",
    label: "Workouts",
    icon: ThunderboltOutlined,
    path: "/admin/workouts",
    section: "MANAGEMENT",
    enabled: false,
  },
  {
    key: "nutrition",
    label: "Nutrition",
    icon: AppleOutlined,
    path: "/admin/nutrition",
    section: "MANAGEMENT",
    enabled: false,
  },
  {
    key: "subscriptions",
    label: "Subscriptions",
    icon: CreditCardOutlined,
    path: "/admin/subscriptions",
    section: "MANAGEMENT",
    enabled: false,
  },
  {
    key: "gamification",
    label: "Gamification",
    icon: TrophyOutlined,
    path: "/admin/gamification",
    section: "ENGAGEMENT",
    enabled: false,
  },
  {
    key: "notifications",
    label: "Notifications",
    icon: BellOutlined,
    path: "/admin/notifications",
    section: "ENGAGEMENT",
    enabled: false,
  },
  {
    key: "support",
    label: "Support",
    icon: CustomerServiceOutlined,
    path: "/admin/support",
    section: "ENGAGEMENT",
    enabled: false,
  },
  {
    key: "content",
    label: "Content",
    icon: FileTextOutlined,
    path: "/admin/content",
    section: "CONTENT",
    enabled: false,
  },
  {
    key: "faq",
    label: "FAQ",
    icon: QuestionCircleOutlined,
    path: "/admin/faq",
    section: "CONTENT",
    enabled: false,
  },
  {
    key: "translations",
    label: "Translations",
    icon: TranslationOutlined,
    path: "/admin/translations",
    section: "CONTENT",
    enabled: false,
  },
  {
    key: "analytics",
    label: "Analytics",
    icon: BarChartOutlined,
    path: "/admin/analytics",
    section: "ANALYTICS",
    enabled: false,
  },
  {
    key: "ai",
    label: "AI",
    icon: RobotOutlined,
    path: "/admin/ai",
    section: "ANALYTICS",
    enabled: false,
  },
  {
    key: "audit-logs",
    label: "Audit Logs",
    icon: AuditOutlined,
    path: "/admin/audit-logs",
    section: "SYSTEM",
    enabled: false,
  },
  {
    key: "settings",
    label: "Settings",
    icon: SettingOutlined,
    path: "/admin/settings",
    section: "SYSTEM",
    enabled: false,
  },
];

// Ordered list of section labels, controls the group render order.
export const navigationSections = [
  "MAIN",
  "MANAGEMENT",
  "ENGAGEMENT",
  "CONTENT",
  "ANALYTICS",
  "SYSTEM",
];
